// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9d6JcQVeejuUFoUfqPWqZYhlySYDSB0',
    appId: '1:35260488507:web:001595ac78e67fb174751e',
    messagingSenderId: '35260488507',
    projectId: 'exams-d84b4',
    authDomain: 'exams-d84b4.firebaseapp.com',
    databaseURL: 'https://exams-d84b4-default-rtdb.firebaseio.com',
    storageBucket: 'exams-d84b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBylQ32MRCetoUN5p1aK_2IA7PtzMfYRTQ',
    appId: '1:35260488507:android:57b49a40085e4a5974751e',
    messagingSenderId: '35260488507',
    projectId: 'exams-d84b4',
    databaseURL: 'https://exams-d84b4-default-rtdb.firebaseio.com',
    storageBucket: 'exams-d84b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GvdA27QNfy9lIr9d7dmMNz7MOaeGkIk',
    appId: '1:35260488507:ios:f51e24fa2e11592874751e',
    messagingSenderId: '35260488507',
    projectId: 'exams-d84b4',
    databaseURL: 'https://exams-d84b4-default-rtdb.firebaseio.com',
    storageBucket: 'exams-d84b4.appspot.com',
    iosClientId: '35260488507-ernm860p0j0g0sj8t2h0vp2jqpu6tnpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.examsAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GvdA27QNfy9lIr9d7dmMNz7MOaeGkIk',
    appId: '1:35260488507:ios:f51e24fa2e11592874751e',
    messagingSenderId: '35260488507',
    projectId: 'exams-d84b4',
    databaseURL: 'https://exams-d84b4-default-rtdb.firebaseio.com',
    storageBucket: 'exams-d84b4.appspot.com',
    iosClientId: '35260488507-ernm860p0j0g0sj8t2h0vp2jqpu6tnpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.examsAppFlutter',
  );
}
